if(EXISTS "/Users/abhishek2x/Documents/Learnings/Quant/projects/liquid-book/build-tsan/tests/queue_tests_e3b0c442_tests.cmake")
  include("/Users/abhishek2x/Documents/Learnings/Quant/projects/liquid-book/build-tsan/tests/queue_tests_e3b0c442_tests.cmake")
else()
  add_test(queue_tests_NOT_BUILT queue_tests_NOT_BUILT)
endif()
